### ISSUE TITLE
Typo in namespace

### ISSUE THREAD

**Issue by sinnbeck** [saade/filament-fullcalendar#119]
Here https://github.com/saade/filament-fullcalendar/blob/3.x/resources/views/fullcalendar.blade.php#L2

It says `FilamentFullcalendar` but should be `FilamentFullCalendar`

**Comment by saade** [comment]
its already fixed in v3.0.2 90a3adab4ecd1ebd5f04903d4a1993aef9119716

**Comment by markcameron** [comment]
@saade It wasn't fixed in 90a3ada, that only fixed the class name part:

\Saade\FilamentFullcalendar\FilamentFull`C`alendarPlugin::get();

But there's also a lowercase 'c' here:

 \Saade\FilamentFull`c`alendar\FilamentFullCalendarPlugin::get();

So it should be:

 \Saade\FilamentFullCalendar\FilamentFullCalendarPlugin::get();

Made a PR here #139
